// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthQuery struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthResult struct {
	Success      bool   `json:"success"`
	VaildRequest bool   `json:"vaildRequest"`
	UserID       string `json:"userID"`
}

type Home struct {
	HomeID    string  `json:"homeID"`
	Name      string  `json:"name"`
	Address   string  `json:"address"`
	Rent      float64 `json:"rent"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	NumBed    int     `json:"numBed"`
	City      string  `json:"city"`
}

type UniquenessResult struct {
	EmailUnique    bool   `json:"emailUnique"`
	UsernameUnique bool   `json:"usernameUnique"`
	Message        string `json:"message"`
}

type User struct {
	UserID   string `json:"userID"`
	Password string `json:"password"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Work struct {
	WorkID    string  `json:"workID"`
	Name      string  `json:"name"`
	Address   string  `json:"address"`
	City      string  `json:"city"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type DeleteInfo struct {
	UserID   string `json:"userID"`
	ItemType string `json:"itemType"`
	ItemID   string `json:"itemID"`
}

type DeleteResult struct {
	Success     bool   `json:"success"`
	Description string `json:"description"`
}

type ModHome struct {
	UserID    string  `json:"userID"`
	HomeID    string  `json:"homeID"`
	Name      string  `json:"name"`
	Address   string  `json:"address"`
	Rent      float64 `json:"rent"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	NumBed    int     `json:"numBed"`
	City      string  `json:"city"`
}

type ModUser struct {
	UserID   string `json:"userID"`
	Password string `json:"password"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type ModWork struct {
	UserID    string  `json:"userId"`
	WorkID    string  `json:"workID"`
	Name      string  `json:"name"`
	Address   string  `json:"address"`
	City      string  `json:"city"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type NewHome struct {
	Name    string  `json:"name"`
	Address string  `json:"address"`
	Rent    float64 `json:"rent"`
	NumBed  int     `json:"numBed"`
	UserID  string  `json:"userID"`
	City    string  `json:"city"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewWork struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	UserID  string `json:"userID"`
	City    string `json:"city"`
}
